file_format: "1"
id: crater
name: Crater
type: shield
url: 
requires: [nice_nano_v2]
exposes: [nice_view]
features:
  - keys
  - encoder
  - display
  - underglow
siblings:
  - crater_left
  - crater_right